import { CompletedOperationalTask, OperationalTask, StrategicInsight } from "@/types";

export const strategicInsightsSeed: StrategicInsight[] = [
  {
    id: "insight-1",
    title: "Konverteringseffektiviteten er svekket",
    summary:
      "Konverteringseffektiviteten falt etter at broad match-utvidelse okte trafikk med lav intensjon.",
    confidence: 88,
    sourceChannels: ["googleAds", "ga4", "crm"],
  },
  {
    id: "insight-2",
    title: "Ubalanse mellom SEO og betalt sok",
    summary:
      "Landingssider med sterk SEO-ytelse understottes i for liten grad av betalt sok.",
    confidence: 84,
    sourceChannels: ["searchConsole", "googleAds", "bigQuery"],
  },
  {
    id: "insight-3",
    title: "Risiko i mobil lead-kvalitet",
    summary:
      "Forringelse i lead-kvalitet ser ut til a vere konsentrert i mobile prospekteringskampanjer.",
    confidence: 76,
    sourceChannels: ["ga4", "googleAds", "floodlight"],
  },
  {
    id: "insight-4",
    title: "Skjev budsjettallokering",
    summary:
      "Merkevarekampanjer er fortsatt budsjettbegrenset, mens kampanjer med lav effektivitet skaleres videre.",
    confidence: 81,
    sourceChannels: ["googleAds", "cm360", "dv360"],
  },
];

export const operationalTasks: OperationalTask[] = [
  {
    id: "task-1",
    title: "Begrens broad match i ikke-merkevarekampanjer",
    category: "ppc",
    impact: 9,
    confidence: 8,
    complexity: 4,
    scale: 8,
    estimatedBusinessEffect: "Forbedre ROAS med 8-12% innen 3 uker",
    reasoning: "Andel bortkastet budsjett har okt i broad match-segmenter med lav CRM-lukkerate.",
    owner: "Ansvarlig for betalt media",
    dueDate: "2026-05-24",
  },
  {
    id: "task-2",
    title: "Flytt budsjett til merkevareord med hoy intensjon",
    category: "bidding",
    impact: 8,
    confidence: 9,
    complexity: 3,
    scale: 7,
    estimatedBusinessEffect: "Gjenopprett impression share og reduser tapt merkevareettersporsel",
    reasoning: "Merkevareettersporsel er underfinansiert til tross for bedre effektivitet og lukkerate.",
    owner: "Performancedirektor",
    dueDate: "2026-05-22",
  },
  {
    id: "task-3",
    title: "Løs attribusjonsbrudd mellom GA4 og CRM",
    category: "attribution",
    impact: 7,
    confidence: 7,
    complexity: 5,
    scale: 8,
    estimatedBusinessEffect: "Gjenopprett tillit til rapportering for investeringsbeslutninger",
    reasoning: "Lead-kvalitet per kanal fremstar lavere enn faktisk pa grunn av ufullstendig nedstromsmapping.",
    owner: "Analyseingenior",
    dueDate: "2026-05-27",
  },
  {
    id: "task-4",
    title: "Prioriter tekniske SEO-forbedringer fra crawl",
    category: "seo",
    impact: 7,
    confidence: 8,
    complexity: 4,
    scale: 6,
    estimatedBusinessEffect: "Ok synlighet pa ikke-merkevare for prioriterte kommersielle sider",
    reasoning: "Crawl-dybde og treg indeksering hemmer rangeringspotensialet pa konverterende malsider.",
    owner: "SEO-strateg",
    dueDate: "2026-05-29",
  },
  {
    id: "task-5",
    title: "Reduser friksjon i mobilskjema pa LP-klyngen",
    category: "landing-page",
    impact: 8,
    confidence: 7,
    complexity: 6,
    scale: 7,
    estimatedBusinessEffect: "Ok kvalifisert mobil konverteringsrate med 10-15%",
    reasoning: "Sesjonsopptak og hoy bounce viser tydelig frafall i steg to.",
    owner: "CRO-spesialist",
    dueDate: "2026-05-30",
  },
  {
    id: "task-6",
    title: "Valider Floodlight-hendelsestaksonomi",
    category: "tracking",
    impact: 6,
    confidence: 8,
    complexity: 3,
    scale: 5,
    estimatedBusinessEffect: "Forbedre signalintegritet i attribusjon pa tvers av plattformer",
    reasoning: "Ulike hendelsesetiketter begrenser rene koblinger mellom GMP- og CRM-resultattabeller.",
    owner: "MarTech-ansvarlig",
    dueDate: "2026-05-26",
  },
];

export const completedOperationalTasks: CompletedOperationalTask[] = [
  {
    id: "completed-task-1",
    title: "Kartlegg og fjern dupliserte titteltagger pa tjenestesider",
    category: "seo",
    owner: "SEO-strateg",
    completedDate: "2026-05-11",
    outcome: "Andelen dupliserte titler falt fra 18% til 4% pa indekserte malsider.",
  },
  {
    id: "completed-task-2",
    title: "Gjenopprett GA4-konverteringsmapping for lead_form_submit",
    category: "tracking",
    owner: "Analyseingenior",
    completedDate: "2026-05-09",
    outcome: "Gjenopprettet 12 dager med manglende konverteringshendelser i rapporteringen.",
  },
  {
    id: "completed-task-3",
    title: "Stram inn budsjetttak og pacingregler for merkevarekampanjer",
    category: "bidding",
    owner: "Performancedirektor",
    completedDate: "2026-05-07",
    outcome: "Merkevare impression share okte med 9,3 poeng med lavere CPC-variasjon.",
  },
  {
    id: "completed-task-4",
    title: "Forbedre rekkefolge i mobilskjema for lead-flyt",
    category: "landing-page",
    owner: "CRO-spesialist",
    completedDate: "2026-05-05",
    outcome: "Frafall i steg to ble redusert med 14% pa de viktigste betalte landingssidene.",
  },
];
