import { OperationalTask, StrategicInsight } from "@/types";

export const strategicInsightsSeed: StrategicInsight[] = [
  {
    id: "insight-1",
    title: "Conversion efficiency softened",
    summary:
      "Conversion efficiency declined after broad match expansion increased low-intent search traffic.",
    confidence: 88,
    sourceChannels: ["googleAds", "ga4", "crm"],
  },
  {
    id: "insight-2",
    title: "SEO and paid misalignment",
    summary:
      "High-performing SEO landing pages are under-supported by paid search activity.",
    confidence: 84,
    sourceChannels: ["searchConsole", "googleAds", "bigQuery"],
  },
  {
    id: "insight-3",
    title: "Mobile lead quality risk",
    summary:
      "Lead quality deterioration appears concentrated in mobile prospecting campaigns.",
    confidence: 76,
    sourceChannels: ["ga4", "googleAds", "floodlight"],
  },
  {
    id: "insight-4",
    title: "Budget allocation gap",
    summary:
      "Branded campaigns remain budget constrained while low-efficiency campaigns continue scaling.",
    confidence: 81,
    sourceChannels: ["googleAds", "cm360", "dv360"],
  },
];

export const operationalTasks: OperationalTask[] = [
  {
    id: "task-1",
    title: "Constrain broad match in non-brand campaigns",
    category: "ppc",
    impact: 9,
    confidence: 8,
    complexity: 4,
    scale: 8,
    estimatedBusinessEffect: "Improve ROAS by 8-12% within 3 weeks",
    reasoning: "Waste concentration increased in broad match cohorts with low CRM close rates.",
    owner: "Paid Media Lead",
    dueDate: "2026-05-24",
  },
  {
    id: "task-2",
    title: "Redirect spend to high-intent branded terms",
    category: "bidding",
    impact: 8,
    confidence: 9,
    complexity: 3,
    scale: 7,
    estimatedBusinessEffect: "Recover impression share and reduce lost branded demand",
    reasoning: "Branded demand remains underfunded despite superior efficiency and close-rate quality.",
    owner: "Performance Director",
    dueDate: "2026-05-22",
  },
  {
    id: "task-3",
    title: "Resolve GA4 to CRM attribution breakpoints",
    category: "attribution",
    impact: 7,
    confidence: 7,
    complexity: 5,
    scale: 8,
    estimatedBusinessEffect: "Restore reporting confidence for executive investment decisions",
    reasoning: "Channel-level lead quality appears understated due to incomplete downstream mapping.",
    owner: "Analytics Engineer",
    dueDate: "2026-05-27",
  },
  {
    id: "task-4",
    title: "Prioritise technical SEO crawl fixes",
    category: "seo",
    impact: 7,
    confidence: 8,
    complexity: 4,
    scale: 6,
    estimatedBusinessEffect: "Lift non-brand visibility across priority commercial pages",
    reasoning: "Crawl depth and indexation lag are suppressing ranking potential on converting templates.",
    owner: "SEO Strategist",
    dueDate: "2026-05-29",
  },
  {
    id: "task-5",
    title: "Reduce mobile form friction on LP cluster",
    category: "landing-page",
    impact: 8,
    confidence: 7,
    complexity: 6,
    scale: 7,
    estimatedBusinessEffect: "Increase qualified mobile conversion rate by 10-15%",
    reasoning: "Session recordings and high bounce patterns show interaction drop-off at step two.",
    owner: "CRO Specialist",
    dueDate: "2026-05-30",
  },
  {
    id: "task-6",
    title: "Validate Floodlight event taxonomy",
    category: "tracking",
    impact: 6,
    confidence: 8,
    complexity: 3,
    scale: 5,
    estimatedBusinessEffect: "Improve cross-platform attribution signal integrity",
    reasoning: "Inconsistent event labels limit clean joins between GMP and CRM outcome tables.",
    owner: "MarTech Manager",
    dueDate: "2026-05-26",
  },
];
